Portfolio Management/Models/StaffSkillViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio_Management.Models
{
    public class StaffSkillViewModel
    {
        public int StaffID { get; set; }
        public int StaffSKillID { get; set; }

    }

    public class EditStaffSkillViewModel
    {
        public int StaffID { get; set; }

        public int StaffSkillID { get; set; }
    }

    public class AddSKillViewModel
    {
        public int SkillID { get; set; }
        public int StaffID { get; set; }



        public Staff staff { get; set; }

        
    }

}

Portfolio Management/Models/Staff_Skill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Skill
    {
        public int Staff_ID { get; set; }
        public int Skill_ID { get; set; }
        public short Proficiency_ID { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Adm_Proficiency Adm_Proficiency { get; set; }
        public virtual Ref_Skill Ref_Skill { get; set; }
        public virtual Staff Staff { get; set; }
    }
}

Portfolio Management/Controllers/Staff_SkillController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Portfolio_Management.Models;
using Microsoft.AspNet.Identity;

using System.Diagnostics;

namespace Portfolio_Management.Controllers
{
    public class Staff_SkillController : ApplicationBaseController
    {
        private PMDataEntities db = new PMDataEntities();

        // GET: Staff_Skill
        public ActionResult Index()
        {
            var staff_Skills = db.Staff_Skills.Include(s => s.Adm_Proficiency).Include(s => s.Ref_Skill).Include(s => s.Staff);
            return View(staff_Skills.ToList());
        }

        // GET: Staff_Skill/Details/5
        public ActionResult Details(int? staff_id, int? skill_id)
        {
            if (staff_id == null || skill_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff_Skill staff_Skill = db.Staff_Skills.Find(staff_id, skill_id);
            if (staff_Skill == null)
            {
                return HttpNotFound();
            }
            return View(staff_Skill);
        }

        // GET: Staff_Skill/Create
        public ActionResult Create(int? id)
        {
            ViewBag.Proficiency_ID = new SelectList(db.Adm_Proficiencies, "Proficiency_ID", "Proficiency");
            ViewBag.Skill_ID = new SelectList(db.Ref_Skills, "ID", "Skill");
            if (ModelState.IsValid && id != null)
                ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name", id);
            else
                ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name");

            ViewBag.DateTime = DateTime.Now;
            return View();
        }

        // POST: Staff_Skill/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Staff_ID,Skill_ID,Proficiency_ID,Created_On,Created_By,Modified_On,Modified_By")] Staff_Skill staff_Skill)
        {
            if (ModelState.IsValid)
            {
                db.Staff_Skills.Add(staff_Skill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DateTime = DateTime.Now;
            ViewBag.Proficiency_ID = new SelectList(db.Adm_Proficiencies, "Proficiency_ID", "Proficiency", staff_Skill.Proficiency_ID);
            ViewBag.Skill_ID = new SelectList(db.Ref_Skills, "ID", "Skill", staff_Skill.Skill_ID);
            ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name", staff_Skill.Staff_ID);
            
            return View(staff_Skill);
        }

        // GET: Staff_Skill/Edit/5
        public ActionResult Edit(int? staff_id, int? skill_id)
        {
            //int staffID;

            if (staff_id == null || skill_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //staffID = (int) id;
            Staff_Skill staff_Skill = db.Staff_Skills.Include(x => x.Staff.Staff_Skill).SingleOrDefault(x => x.Staff_ID == staff_id && x.Skill_ID == skill_id);
            //Staff_Skill staff_Skill = db.Staff_Skills.SingleOrDefault(x => x.Staff_ID == id);
            if (staff_Skill == null)
            {
                return HttpNotFound();
            }
            ViewBag.Proficiency_ID = new SelectList(db.Adm_Proficiencies, "Proficiency_ID", "Proficiency", staff_Skill.Proficiency_ID);
            ViewBag.Skill_ID = new SelectList(db.Ref_Skills, "ID", "Skill", staff_Skill.Skill_ID);
            ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name", staff_Skill.Staff_ID);

            ViewBag.DateTime = DateTime.Now;
            return View(staff_Skill);
        }

        // POST: Staff_Skill/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Staff_ID,Skill_ID,Proficiency_ID,Created_On,Created_By,Modified_On,Modified_By")] Staff_Skill staff_Skill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff_Skill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Proficiency_ID = new SelectList(db.Adm_Proficiencies, "Proficiency_ID", "Proficiency", staff_Skill.Proficiency_ID);
            ViewBag.Skill_ID = new SelectList(db.Ref_Skills, "ID", "Skill", staff_Skill.Skill_ID);
            ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name", staff_Skill.Staff_ID);
            return View(staff_Skill);
        }

        [HttpGet]
        public ActionResult ManageStaffSkillModal(int id)
        {
            StaffDashboardViewModel sdVM = new StaffDashboardViewModel();
            sdVM.SelectedStaffData.Staff = db.Staffs.Find(id);

            //Load all proficiencies
            foreach (var proficiency in db.Adm_Proficiencies)
            {
                sdVM.AllSkillsData.Proficiencies.Add(proficiency);
            }

            //For each skill in the list of ALL skills
            foreach (var skill in db.Ref_Skills)
            {
                sdVM.AllSkillsData.Skills.Add(skill);

                //Create a view model, map to properties in Ref_Skills
                ManageSkillViewModel manageSkillVM = new ManageSkillViewModel();
                manageSkillVM.SkillID = skill.ID;
                manageSkillVM.SkillName = skill.Skill;
                manageSkillVM.StaffID = sdVM.SelectedStaffData.Staff.ID;
                manageSkillVM.StaffSkillRadioButtonID = skill.ID + ", " + sdVM.SelectedStaffData.Staff.ID;

                //Get relevant skill data if user has the skill
                foreach (var mySkill in db.Staff_Skills.Where(x => x.Staff_ID == sdVM.SelectedStaffData.Staff.ID))
                {
                    if (mySkill.Skill_ID == skill.ID)
                    {
                        manageSkillVM.HasSkill = true;
                        manageSkillVM.ProficiencyID = db.Staff_Skills.FirstOrDefault(x => x.Skill_ID == skill.ID).Proficiency_ID;
                        manageSkillVM.ProficiencyName = db.Staff_Skills.FirstOrDefault(x => x.Skill_ID == skill.ID).Adm_Proficiency.Proficiency;
                        manageSkillVM.RemoveSKill = false;
                    }
                }

                sdVM.ManageSkillDataList.Add(manageSkillVM); //Add view model to list of view models
            }

            return PartialView("_SkillModal", sdVM);
        }
        // StaffSkillAction: POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageStaffSkillModal(StaffDashboardViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Iterate over all skills user may have added/modified using client-filled form data
                foreach (var newStaffSkill in model.ManageSkillDataList)
                {
                    //Staff has this skill and does not want to remove it (possible modification)
                    if (newStaffSkill.HasSkill == true && newStaffSkill.RemoveSKill == false)
                    {
                        Staff_Skill skillToModify = new Staff_Skill();
                        skillToModify = db.Staff_Skills.Where(x => x.Staff_ID == newStaffSkill.StaffID)
                            .Where(x => x.Skill_ID == newStaffSkill.SkillID).SingleOrDefault();

                        //User has modified the proficiency
                        if (skillToModify.Proficiency_ID != newStaffSkill.ProficiencyID)
                        {
                            skillToModify.Proficiency_ID = newStaffSkill.ProficiencyID;
                            skillToModify.Modified_By = getCurrentUserFullName();
                            skillToModify.Modified_On = System.DateTime.Now;
                            db.Staff_Skills.Attach(skillToModify);
                            var entry = db.Entry(skillToModify);
                            entry.State = EntityState.Modified;
                        }
                    }
                    //Staff has this skill and wants to remove it
                    else if (newStaffSkill.HasSkill == true && newStaffSkill.RemoveSKill == true)
                    {
                        Staff_Skill skillToRemove = new Staff_Skill();
                        skillToRemove = db.Staff_Skills.Where(x => x.Staff_ID == newStaffSkill.StaffID)
                            .Where(x => x.Skill_ID == newStaffSkill.SkillID).SingleOrDefault();

                        db.Staff_Skills.Attach(skillToRemove);
                        db.Staff_Skills.Remove(skillToRemove);
                    }
                    //Staff does not have this skill
                    else if (newStaffSkill.HasSkill == false)
                    {
                        //If the proficiency was selected, user wants to add this skill
                        if (newStaffSkill.ProficiencyID != 0) 
                        {
                            Staff_Skill newSkill = new Staff_Skill();
                            newSkill.Skill_ID = newStaffSkill.SkillID;
                            newSkill.Staff_ID = newStaffSkill.StaffID;
                            newSkill.Proficiency_ID = newStaffSkill.ProficiencyID;
                            newSkill.Created_By = getCurrentUserFullName();
                            newSkill.Created_On = System.DateTime.Now;
                            newSkill.Modified_By = getCurrentUserFullName();

Portfolio Management/Views/Staff_Skill/Create.cshtml
@model Portfolio_Management.Models.Staff_Skill

@{
    ViewBag.Title = "Create";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Staff Skill</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Create</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Staff_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("Staff_ID", null,"-- Select Staff --", htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Staff_ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Skill_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("Skill_ID", null,"-- Select a Skill --", htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Skill_ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Proficiency_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("Proficiency_ID", null, "-- Select a Proficiency --",htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Proficiency_ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                @Html.HiddenFor(model => model.Created_On, new { @Value = ViewBag.DateTime })
                                @Html.HiddenFor(model => model.Created_By, new { @Value = ViewData["FullName"] })
                                @Html.HiddenFor(model => model.Modified_On, new { @Value = ViewBag.DateTime })
                                @Html.HiddenFor(model => model.Modified_By, new { @Value = ViewData["FullName"] })
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                        <div>
                            @Html.ActionLink("Back to Staff Skills", "Index")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

Portfolio Management/Views/Staff_Skill/Delete.cshtml
@model Portfolio_Management.Models.Staff_Skill


@{
    ViewBag.Title = "Delete";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Staff Skill</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Delete </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                       
                        <h3>Are you sure you want to delete this Skill?</h3>
                        <div>
                            <h4>Staff_Skill</h4>
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Created_On)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Created_On)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Created_By)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Created_By)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Modified_On)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Modified_On)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Modified_By)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Modified_By)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Adm_Proficiency.Proficiency)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Adm_Proficiency.Proficiency)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Ref_Skill.Skill)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Ref_Skill.Skill)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Staff.Staff_Name)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Staff.Staff_Name)
                                </dd>

                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Delete" class="btn btn-default" /> |
                                    @Html.ActionLink("Back to List", "Index")
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

Portfolio Management/Views/Staff_Skill/Details.cshtml
@model Portfolio_Management.Models.Staff_Skill


@{
    ViewBag.Title = "Details";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Staff Skill</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Details</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div>

                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Created_On)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Created_On)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Created_By)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Created_By)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Modified_On)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Modified_On)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Modified_By)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Modified_By)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Adm_Proficiency.Proficiency)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Adm_Proficiency.Proficiency)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Ref_Skill.Skill)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Ref_Skill.Skill)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Staff.Staff_Name)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Staff.Staff_Name)
                                </dd>

                            </dl>
                        </div>
                        <p>
                            @Html.ActionLink("Edit", "Edit", new { Staff_ID = Model.Staff_ID, Skill_ID = Model.Skill_ID }) |
                            @Html.ActionLink("Back to List", "Index")
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

Portfolio Management/Views/Staff_Skill/_SkillModal.cshtml
@model Portfolio_Management.Models.StaffDashboardViewModel
<div class="container">
    <!-- Modal -->
    <div id='staffSkillsModal' class="modal fade" role="dialog">
        <div class="modal-dialog" style="width:800px;">
            <!-- Modal content-->
            <div class="modal-content">
                <div id='myModalContent'>
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Modify @Html.DisplayFor(model => model.SelectedStaffData.Staff.First_Name)'s Skills</h4>
                    </div>
                    <div id="modalForm" class="modal-body">
                        @using (Html.BeginForm("ManageStaffSkillModal", "Staff_Skill"))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal" style="text-align:center">
                                <div class="form-group">
                                    <div class="col-md-10">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" style="width:100%;">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        @Html.DisplayNameFor(model => Model.SelectedStaffData.StaffSkills[0].Ref_Skill.Skill)
                                                    </th>
                                                    @foreach (var prof_item in Model.AllSkillsData.Proficiencies)
                                                    {
                                                        <th>
                                                            @Html.DisplayFor(model => prof_item.Proficiency)
                                                        </th>
                                                    }
                                                    <th>
                                                        @Html.DisplayNameFor(model => Model.ManageSkillDataList[0].RemoveSKill)
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody id="modal-skill-table-body">
                                                @for (var i = 0; i < Model.ManageSkillDataList.Count; i++)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => Model.ManageSkillDataList[i].SkillName)
                                                            @Html.HiddenFor(modelItem => Model.ManageSkillDataList[i].SkillName)
                                                        </td>
                                                        @foreach (var prof in Model.AllSkillsData.Proficiencies)
                                                        {
                                                            <td style="padding:0px 4px 0px 0px; text-align:center;">
                                                                @Html.RadioButtonFor(modelItem => Model.ManageSkillDataList[i].ProficiencyID, prof.Proficiency_ID)<br />
                                                                @Html.ValidationMessageFor(modelItem => Model.ManageSkillDataList[i].ProficiencyID, "", new { @class = "text-danger" })
                                                            </td>
                                                        }
                                                        <td style="padding:0px 4px 0px 0px; text-align:center;">
                                                            @if(Model.ManageSkillDataList[i].HasSkill == true)
                                                            {
                                                                @Html.CheckBoxFor(modelItem => Model.ManageSkillDataList[i].RemoveSKill)
                                                                @Html.ValidationMessageFor(modelItem => Model.ManageSkillDataList[i].RemoveSKill, "", new { @class = "text-danger" })
                                                            }

                                                        </td>
                                                        @Html.HiddenFor(modelItem => Model.ManageSkillDataList[i].SkillID)
                                                        @Html.HiddenFor(modelItem => Model.ManageSkillDataList[i].SkillName)
                                                        @Html.HiddenFor(modelItem => Model.ManageSkillDataList[i].StaffID)
                                                        @Html.HiddenFor(modelItem => Model.ManageSkillDataList[i].HasSkill)
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10" >
                                        <input type="submit" value="Submit" class="btn btn-default" />
                                    </div>
                                </div>

                            </div>
                        }
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>