Portfolio Management/Models/Education.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int ID { get; set; }
        public int Staff_ID { get; set; }
        public string School { get; set; }
        public short Degree_ID { get; set; }
        public System.DateTime Completed_Date { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Adm_Degree Adm_Degree { get; set; }
        public virtual Staff Staff { get; set; }
    }
}

Portfolio Management/Controllers/EducationsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Portfolio_Management.Models;

namespace Portfolio_Management.Controllers
{
    public class EducationsController : ApplicationBaseController
    {
        private PMDataEntities db = new PMDataEntities();

        [HttpGet]
        public ActionResult ManageStaffEducationsModal(int id)
        {
            StaffDashboardViewModel sdVM = new StaffDashboardViewModel();
            sdVM.SelectedStaffData.Staff = db.Staffs.Find(id);
            int i = 0;

            //get user's educations
            List<Education> selectedStaffEducations = db.Educations.Include(x => x.Staff).Where(x => x.Staff_ID == sdVM.SelectedStaffData.Staff.ID).ToList();

            //Map user's educations to view model: ManageEducationsDataList
            foreach (var education in selectedStaffEducations)
            {
                ManageStaffEducationsViewModel manageEducationsVM = new ManageStaffEducationsViewModel();
                manageEducationsVM.StaffID = education.Staff_ID;
                manageEducationsVM.School = education.School;
                manageEducationsVM.DegreeID = education.Degree_ID;
                manageEducationsVM.CompletedDate = education.Completed_Date;
                manageEducationsVM.HasEducation = true;
                manageEducationsVM.RemoveEducation = false;
                manageEducationsVM.StaffName = education.Staff.Staff_Name;
                manageEducationsVM.EducationID = education.ID;
                manageEducationsVM.CurrentListIndex = i;
                manageEducationsVM.IsNewSkill = false;

                i++;
                sdVM.ManageEducationsDataList.Add(manageEducationsVM);
            }


            ViewBag.DegSelectList = new SelectList(db.Adm_Degrees, "ID", "Degree");
            ViewBag.ListDegrees = db.Adm_Degrees;

            return PartialView("_staffEducationsModal", sdVM);
        }

        public ActionResult addSingleEducation()
        {
            ViewBag.ListDegrees = db.Adm_Degrees;
            ViewBag.DegSelectList = new SelectList(db.Adm_Degrees, "ID", "Degree");

            ManageStaffEducationsViewModel newSEVM = new ManageStaffEducationsViewModel();
            newSEVM.IsNewSkill = true;
            return PartialView("_singleStaffEducation", newSEVM);
        }

        // StaffSkillAction: POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageStaffEducationsModal(StaffDashboardViewModel model)
        {
            string currentUserName = getCurrentUserFullName();
            DateTime currentTime = System.DateTime.Now;
            DateTime nullDateTimeValue = new DateTime(0001, 1, 1, 12, 0, 0);

            if (ModelState.IsValid)
            {
                //create copy of data while we enumerate through the model
                List<ManageStaffEducationsViewModel> postIteratorCopy = model.ManageEducationsDataList;

                foreach (var editedEducation in model.ManageEducationsDataList)
                {
                    //User wants to delete education
                    if (editedEducation.RemoveEducation == true)
                    {
                        if (editedEducation.HasEducation == true)
                        {
                            Education educationToFind = new Education();
                            educationToFind = db.Educations.Where(x => x.ID == editedEducation.EducationID).SingleOrDefault();

                            db.Educations.Attach(educationToFind);
                            db.Educations.Remove(educationToFind);
                        }
                        else if (editedEducation.IsNewSkill == true)
                        {
                            postIteratorCopy.Remove(editedEducation);
                        }
                    }

                    //Check if user edited education
                    else if (editedEducation.HasEducation == true && editedEducation.RemoveEducation == false)
                    {
                        Education educationFoundFromDb = new Education();
                        educationFoundFromDb = db.Educations.Where(x => x.ID == editedEducation.EducationID).SingleOrDefault();

                        //User modified a field in their existing Educations
                        if (editedEducation.DegreeID != educationFoundFromDb.Degree_ID ||
                            editedEducation.School != educationFoundFromDb.School ||
                            editedEducation.CompletedDate != educationFoundFromDb.Completed_Date)
                        {
                            educationFoundFromDb.Degree_ID = editedEducation.DegreeID;
                            educationFoundFromDb.School = editedEducation.School;
                            educationFoundFromDb.Completed_Date = editedEducation.CompletedDate;
                            educationFoundFromDb.Staff_ID = editedEducation.StaffID;
                            educationFoundFromDb.Modified_By = currentUserName;
                            educationFoundFromDb.Modified_On = currentTime;

                            db.Educations.Attach(educationFoundFromDb);
                            var entry = db.Entry(educationFoundFromDb);
                            entry.State = EntityState.Modified;
                        }
                    }
                    else if (editedEducation.HasEducation == false)
                    {
                        //User added new Education
                        Education newEducation = new Education();
                        newEducation.Staff_ID = editedEducation.StaffID;
                        newEducation.Degree_ID = editedEducation.DegreeID;
                        newEducation.School = editedEducation.School;
                        newEducation.Completed_Date = editedEducation.CompletedDate;
                        newEducation.Created_By = currentUserName;
                        newEducation.Created_On = currentTime;
                        newEducation.Modified_By = currentUserName;
                        newEducation.Modified_On = currentTime;

                        db.Educations.Add(newEducation);
                    }
                }
            }
            else
            {
                List<string> modelStateErrors = new List<string>();
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        modelStateErrors.Add(error.ErrorMessage);
                    }
                }
            }

            db.SaveChanges();
            return RedirectToAction("Index","Staff");
        }

        // GET: Educations
        public ActionResult Index()
        {
            var educations = db.Educations.Include(e => e.Adm_Degree).Include(e => e.Staff);
            return View(educations.ToList());
        }

        // GET: Educations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Education education = db.Educations.Find(id);
            if (education == null)
            {
                return HttpNotFound();
            }
            return View(education);
        }

        // GET: Educations/Create
        public ActionResult Create(int? id)
        {
            ViewBag.Degree_ID = new SelectList(db.Adm_Degrees, "ID", "Degree");
            ViewBag.DateTime = DateTime.Now;

            if (ModelState.IsValid && id != null)
                ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name", id);
            else
                ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name");

            return View();
        }

        // POST: Educations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Staff_ID,School,Degree_ID,Completed_Date,Created_On,Created_By,Modified_On,Modified_By")] Education education)
        {
            if (ModelState.IsValid)
            {
                db.Educations.Add(education);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DateTime = DateTime.Now;
            ViewBag.Degree_ID = new SelectList(db.Adm_Degrees, "ID", "Degree", education.Degree_ID);
            ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name", education.Staff_ID);
            return View(education);
        }

        // GET: Educations/Edit/5
        public ActionResult Edit(int? id, int? staff_id)
        {
            if (id == null || staff_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Education education = db.Educations.SingleOrDefault(x => x.ID == id && x.Staff_ID == staff_id);

            if (education == null)
            {
                return HttpNotFound();
            }
            ViewBag.DateTime = DateTime.Now;
            ViewBag.Degree_ID = new SelectList(db.Adm_Degrees, "ID", "Degree", education.Degree_ID);
            ViewBag.Staff_ID = new SelectList(db.Staffs, "ID", "Staff_Name", education.Staff_ID);
            return View(education);
        }

        // POST: Educations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Portfolio Management/Views/Educations/Create.cshtml
@model Portfolio_Management.Models.Education

@{
    ViewBag.Title = "Create";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Education</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Create</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Staff_ID, "Staff_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("Staff_ID", null, "-- Select Staff --",htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Staff_ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.School, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.School, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.School, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Degree_ID, "Degree_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("Degree_ID", null, "-- Select Degree --",htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Degree_ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Completed_Date, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Completed_Date, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Completed_Date, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                @Html.HiddenFor(model => model.Created_On, new { @Value = ViewBag.DateTime })
                                @Html.HiddenFor(model => model.Created_By, new { @Value = ViewData["FullName"] })
                                @Html.HiddenFor(model => model.Modified_On, new { @Value = ViewBag.DateTime })
                                @Html.HiddenFor(model => model.Modified_By, new { @Value = ViewData["FullName"] })
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

Portfolio Management/Views/Educations/Delete.cshtml
@model Portfolio_Management.Models.Education

@{
    ViewBag.Title = "Delete";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Education</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Delete </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <h3>Are you sure you want to delete this Education?</h3>
                        <div>
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.School)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.School)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Completed_Date)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Completed_Date)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Created_On)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Created_On)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Created_By)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Created_By)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Modified_On)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Modified_On)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Modified_By)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Modified_By)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Adm_Degree.Degree)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Adm_Degree.Degree)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Staff.Staff_Name)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Staff.Staff_Name)
                                </dd>

                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Delete" class="btn btn-default" /> |
                                    @Html.ActionLink("Back to List", "Index")
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

Portfolio Management/Views/Educations/Index.cshtml
@model IEnumerable<Portfolio_Management.Models.Education>

@{
    ViewBag.Title = "Index";
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Education</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Educations</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a href="/Educations/Create" role="button" aria-expanded="false"><i class="fa fa-plus-square"></i></a>
                            </li>
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div style="overflow-x:auto">
                            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Staff.Staff_Name)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.School)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Completed_Date)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Adm_Degree.Degree)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Created_On)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Created_By)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Modified_On)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Modified_By)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Staff.Staff_Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.School)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Completed_Date)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Adm_Degree.Degree)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Created_On)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Created_By)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Modified_On)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Modified_By)
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Edit","Educations", new { id = item.ID, staff_id = item.Staff_ID})"><span title="Edit" class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a> |
                                                <a href="@Url.Action("Details","Educations", new { id = item.ID, staff_id = item.Staff_ID})"><span title="Details" class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a> |
                                                <a href="@Url.Action("Delete","Educations", new { id = item.ID, staff_id = item.Staff_ID})"><span title="Delete" class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

Portfolio Management/Views/Educations/_staffEducationsModal.cshtml
@model Portfolio_Management.Models.StaffDashboardViewModel
<div class="container">
    <!-- Modal -->
    <div id='staffEducationsModal' class="modal fade" role="dialog">
        <div class="modal-dialog" style="width:800px;">
            <!-- Modal content-->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 modal-content" >
                <div id='myModalContent'>
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Modify @Html.DisplayFor(model => model.SelectedStaffData.Staff.First_Name)'s Education</h4>
                    </div>
                    <div id="modalForm" class="modal-body">
                        @using (Html.BeginForm("ManageStaffEducationsModal", "Educations"))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-horizontal" style="text-align:center">
                                <div class="form-group">
                                    <div class="col-md-10" style="text-align:center">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" style="width:100%;">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        @Html.DisplayNameFor(model => Model.AllEducationsData.Educations[0].Adm_Degree.Degree)
                                                    </th>
                                                    <th>
                                                        @Html.DisplayNameFor(model => Model.AllEducationsData.Educations[0].School)
                                                    </th>
                                                    <th>
                                                        @Html.DisplayNameFor(model => Model.AllEducationsData.Educations[0].Completed_Date)
                                                    </th>
                                                    <th>
                                                        @Html.DisplayNameFor(model => Model.ManageEducationsDataList[0].RemoveEducation)
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody id="modal-skill-table-body">

                                                @foreach (var staffEducation in Model.ManageEducationsDataList)
                                                {
                                                    Html.RenderPartial("_singleStaffEducation", staffEducation);
                                                }
                                            </tbody>
                                        </table>
                                        
                                    </div>
                                </div>
                                <div style="text-align:center" class="form-group">
                                    <input type="submit" value="Submit" class="btn btn-default" />
                                </div>
                            </div>
                        }
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="button" id="addemployee" name="addemployee" value="Add Education" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $('#addemployee').on('click', function () {
            $.ajax({
                async: false,
                url: '/Educations/addSingleEducation'
            }).success(function (partialView) {
                $('#modal-skill-table-body').append(partialView);
            });
        });

        //$("#deleteRow").live("click", function () {
        //    $(this).parents("#employeeRow:first").remove();
        //    return false;
        //});
    </script>
</div>